fail_fast: true
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.2
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key

- repo: local
  hooks:
  - id: eslint
    name: eslint-local
    entry: yarn lint
    language: system
    types: [javascript]
    exclude: >
            (?x)^(
                .+\.config\.js|
                server\.js|
                \.eslintrc\.js
            )$
    pass_filenames: true
  - id: missing-migrations