version: '3.9'
services:
    backend:
        container_name: backend
        build: 
            dockerfile: backend/Dockerfile
            context: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/src
        env_file:
            - .env.local
        depends_on:
            - db

    db:
        container_name: db
        image: postgres
        env_file:
            - .env.local

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025' # smtp server
            - '8025:8025' # web ui

volumes:
    backend_db:
    kb_db:
